server:
  port: 1101

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.99:8888/eureka
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.99
    instance-id: ${eureka.instance.ip-address}:${server.port}

spring:
  application:
    name: eureka-listener
  rabbitmq:
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 1000
          multiplier: 1.0
    addresses: 192.168.0.99:5672, 192.168.0.99:5673
  redis:
    sentinel:
      master: mymaster
      nodes: 192.168.0.99:26379, 192.168.0.99:16379
    database: 0
    port: 6379
    timeout: 3000

logging:
  file:
    path: /log
    name: listener.log
  level:
    com:
      example:
        DEBUG


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
